{
 "title": "IoT",
 "time": { "from": "2022-07-16T07:44:02.000Z", "to": "2022-07-16T11:33:14.000Z" },
 "panels": [
  {
   "title": "Current Temperature (°C)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature FROM temperature ORDER BY ID DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Current Oxygen Percentage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT oxygen AS \"%\" FROM oxygen ORDER BY ID DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperature Trend (last hour)",
   "type": "timeseries",
   "description": "Trend of the temperature values in the last hour",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  temperature\nFROM temperature\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Oxygen Trend (last hour)",
   "type": "timeseries",
   "description": "Trend of the percentage of oxygen in the air in the last hour",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  oxygen\nFROM oxygen\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Most Recent Fire Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  TIMEDIFF(MAX(timestamp), MIN(timestamp)) AS 'value'\nFROM fire_alarm\nWHERE fire_index = (SELECT MAX(fire_index) FROM fire_alarm);"
    }
   ]
  }
 ]
}